# Generated by Django 3.1.6 on 2021-03-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonlar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefonlar',
            old_name='Brend',
            new_name='brend',
        ),
        migrations.RenameField(
            model_name='telefonlar',
            old_name='Memory',
            new_name='memory',
        ),
        migrations.RenameField(
            model_name='telefonlar',
            old_name='Type',
            new_name='type',
        ),
    ]
